### ISSUE TITLE
Site is not updating 

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#117] opened 2022-05-20 01:51 UTC
@yaelrst @jheretic @harumhelmy I have published a new article in the CMS, but its not showing up on the site. The site generally doesn't seem to be posting new content or updating existing content. 
https://recoding.tech/article/supporting-local-news-and-journalism-in-the-era-of-big-tech

**Comment by harumhelmy** [comment] 2022-05-20 13:35
Hey Ben! Sorry to hear that the site wasn't updating last night! I just re-deployed the production site on Netlify and I can see the article published now. I'll be investigating the logs from last night to see what might have happened, but my guess is that the revert work we did might have caused some confusion on the backend. 

Can you let me know whether there are any new content/updates you're not seeing?

**Comment by harumhelmy** [comment] 2022-05-20 13:57
Woohoo, @jheretic just helped me realize what was going on! Sorry for the temporary stress there. The problem is fixed now, and any updates you make in Sanity should trigger an update of the production site. I'm available all day today until 4:30 except for 11:30-1 to be on hand if you notice anything else amiss @gt150.

**Comment by gt150** [comment] 2022-05-20 14:05
@jheretic @harumhelmy Thanks all. Things look they're working again.

**Comment by gt150** [comment] 2022-05-20 15:17
@harumhelmy @jheretic  Things are stuck again.

**Comment by harumhelmy** [comment] 2022-05-20 15:41
I'm looking into this! So far not seeing any failed builds on Netlify, but watching the deploy logs now.

**Comment by gt150** [comment] 2022-05-20 16:18
@harumhelmy the homepage and the article are now updated.

**Comment by harumhelmy** [comment] 2022-05-20 16:23
Great! Yeah, everything is looking fine and building as normal on the backend, so perhaps what you saw was just a build/deploy process that took a little longer than usual.

**Closed** 2022-07-14 17:48 UTC
Labels: bug, priority: high
