### ISSUE TITLE
Citation lists on the website (aka Latest Headlines & Highlights) are not listing as expected

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#44] opened 2021-12-01 19:50 UTC
On homepage
* This should show the 6 most recently published (by zotero date field) citations

On Search
* This should be in the order of recently published (by zotero date field)

On Topic pages (aka Issues, Policies, Country, and Company)
* This show the most recent 3 in the order of recently published ( by zotero date field) 
* The view all should go to the search page pre-filtered for that topic

**Comment by danblah** [comment] 2021-12-14 17:35
Deadline?

**Comment by harumhelmy** [comment] 2021-12-15 20:48
I have a partial fix for this -- aiming for Tuesday (trying to underpromise and overdeliver!)

**Comment by danblah** [comment] 2022-01-28 17:39
@jheretic @harumhelmy im still not seeing any "Latest headlines & Highlights" on any topic pages (aka Issues, Policies, Country, and Company) as is in the wireframes.

bump bump bump!

**Comment by danblah** [comment] 2022-01-28 19:29
@harumhelmy this a dupe of #23? if so can we close this one?

**Comment by rudietuesdays** [comment] 2022-02-01 15:57
@danblah Yes I believe this is a dupe of #23 which is now fixed, so I'm all for closing this one

**Comment by rudietuesdays** [comment] 2022-02-24 21:13
Closing as a dupe of #23 -- feel free to reopen if needed!

**Closed by rudietuesdays** 2022-02-24 21:13 UTC
Labels: priority: high, needs testing
